# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        self.menuRun = QtWidgets.QMenu(self.menuBar)
        self.menuRun.setObjectName("menuRun")
        self.menuModels = QtWidgets.QMenu(self.menuRun)
        self.menuModels.setObjectName("menuModels")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setEnabled(False)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionRun = QtWidgets.QAction(MainWindow)
        self.actionRun.setObjectName("actionRun")
        self.actionVGG16 = QtWidgets.QAction(MainWindow)
        self.actionVGG16.setObjectName("actionVGG16")
        self.actionVGG19 = QtWidgets.QAction(MainWindow)
        self.actionVGG19.setObjectName("actionVGG19")
        self.actionResNet = QtWidgets.QAction(MainWindow)
        self.actionResNet.setObjectName("actionResNet")
        self.actionInception_V3 = QtWidgets.QAction(MainWindow)
        self.actionInception_V3.setObjectName("actionInception_V3")
        self.actionXception = QtWidgets.QAction(MainWindow)
        self.actionXception.setObjectName("actionXception")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionNormal_Size = QtWidgets.QAction(MainWindow)
        self.actionNormal_Size.setObjectName("actionNormal_Size")
        self.actionFit_to_Window = QtWidgets.QAction(MainWindow)
        self.actionFit_to_Window.setObjectName("actionFit_to_Window")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionNormal_Size)
        self.menuView.addAction(self.actionFit_to_Window)
        self.menuModels.addAction(self.actionVGG16)
        self.menuModels.addAction(self.actionVGG19)
        self.menuModels.addAction(self.actionResNet)
        self.menuModels.addAction(self.actionInception_V3)
        self.menuModels.addAction(self.actionXception)
        self.menuRun.addAction(self.actionRun)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.menuModels.menuAction())
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuRun.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuRun.setTitle(_translate("MainWindow", "Run"))
        self.menuModels.setTitle(_translate("MainWindow", "Models"))
        self.actionRun.setText(_translate("MainWindow", "Run"))
        self.actionRun.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionVGG16.setText(_translate("MainWindow", "VGG16"))
        self.actionVGG19.setText(_translate("MainWindow", "VGG19"))
        self.actionResNet.setText(_translate("MainWindow", "ResNet"))
        self.actionInception_V3.setText(_translate("MainWindow", "Inception V3"))
        self.actionXception.setText(_translate("MainWindow", "Xception"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExit.setText(_translate("MainWindow", "E&xit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionNormal_Size.setText(_translate("MainWindow", "&Normal Size"))
        self.actionNormal_Size.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionFit_to_Window.setText(_translate("MainWindow", "&Fit to Window"))
        self.actionFit_to_Window.setShortcut(_translate("MainWindow", "Ctrl+F"))

